name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      testfile:
        description: 'Path to Cypress test file (leave empty to run all tests)'
        required: false
        default: ''
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Tests
        run: |
          if [ -z "${{ github.event.inputs.testfile }}" ]; then
            echo "🔹 Running all Cypress tests..."
            npx cypress run --browser chrome --headless
          else
            echo "🔹 Running specific Cypress test file: ${{ github.event.inputs.testfile }}"
            npx cypress run --spec "${{ github.event.inputs.testfile }}" --browser chrome --headless
          fi

      - name: Upload Cypress Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload Cypress Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
